CREATE TABLE MAINTABLE (Rollno integer primary key , Namestudents VARCHAR(30));
DESC MAINTABLE;
INSERT INTO MAINTABLE VALUES(1,YUKTI);
UPDATE MAINTABLE SET Namestudents = "ODITI" WHERE Namestudents = "YUKTI";
SELECT * FROM MAINTABLE;
DELETE FROM MAINTABLE 
WHERE Rollno<10;
DROP TABLE MAINTABLE;
